-- AUTHOR: James Daniel Johnson
-- COURSE: CSCI 601 Spring 2026 - Data Modeling and SQL
-- INSTRUCTOR: Dr. John Ravan

DROP SCHEMA IF EXISTS LIBRARY CASCADE ;
CREATE SCHEMA IF NOT EXISTS LIBRARY;
SET SEARCH_PATH TO LIBRARY, PUBLIC;

CREATE TABLE PUBLISHER (
  Name VARCHAR PRIMARY KEY,
  Address VARCHAR NOT NULL UNIQUE,
  Phone VARCHAR NOT NULL UNIQUE
);

CREATE TABLE LIBRARY_BRANCH (
  Branch_id SERIAL PRIMARY KEY,
  Branch_name VARCHAR NOT NULL,
  Address VARCHAR NOT NULL UNIQUE
);

CREATE TABLE BORROWER (
  Card_no SERIAL PRIMARY KEY,
  Name VARCHAR NOT NULL,
  Address VARCHAR NOT NULL,
  Phone VARCHAR NOT NULL,
  CONSTRAINT UQ_BORROWER UNIQUE (Name, Address, Phone)
);

CREATE TABLE BOOK (
  Book_id SERIAL PRIMARY KEY,
  Title VARCHAR NOT NULL,
  Publisher_name VARCHAR REFERENCES PUBLISHER(Name)
);

CREATE TABLE BOOK_AUTHORS (
  Book_id INTEGER REFERENCES BOOK(Book_id) NOT NULL,
  Author_name VARCHAR NOT NULL,
  CONSTRAINT PK_BOOK_AUTHORS PRIMARY KEY (Book_id, Author_name)
);

CREATE TABLE BOOK_COPIES (
  Book_id INTEGER REFERENCES BOOK(Book_id) NOT NULL,
  Branch_id INTEGER REFERENCES LIBRARY_BRANCH(Branch_id) NOT NULL,
  No_of_copies INTEGER NOT NULL,
  CONSTRAINT PK_BOOK_COPIES PRIMARY KEY (Book_id, Branch_id)
);

CREATE TABLE BOOK_LOANS (
  Book_id INTEGER REFERENCES BOOK(Book_id) NOT NULL,
  Branch_id INTEGER REFERENCES LIBRARY_BRANCH(Branch_id) NOT NULL,
  Card_no INTEGER REFERENCES BORROWER(Card_no) NOT NULL,
  Date_out DATE NOT NULL,
  Due_date DATE NOT NULL,
  CONSTRAINT PK_BOOK_LOANS PRIMARY KEY (Book_id, Branch_id, Card_no),
  CONSTRAINT CK_DUE_DATE CHECK (Due_date > Date_out)
);

-- END OF Library DDL
