-- AUTHOR: James Daniel Johnson
-- COURSE: CSCI 601 Spring 2026 - Data Modeling and SQL
-- INSTRUCTOR: Dr. John Ravan

-- Create the LIBRARY schema
CREATE SCHEMA LIBRARY;

SET search_path TO LIBRARY, public;

CREATE TABLE PUBLISHER (
  Name VARCHAR PRIMARY KEY,
  Address VARCHAR,
  Phone VARCHAR
);

CREATE TABLE LIBRARY_BRANCH (
  Branch_id SERIAL PRIMARY KEY,
  Branch_name VARCHAR,
  Address VARCHAR
);

CREATE TABLE BORROWER (
  Card_no SERIAL PRIMARY KEY,
  Name VARCHAR,
  Address VARCHAR,
  Phone VARCHAR
);

CREATE TABLE BOOK (
  Book_id SERIAL PRIMARY KEY,
  Title VARCHAR,
  Publisher_name VARCHAR REFERENCES PUBLISHER(Name)
);

CREATE TABLE BOOK_AUTHORS (
  Book_id INTEGER REFERENCES BOOK(Book_id) NOT NULL,
  Author_name VARCHAR NOT NULL,
  CONSTRAINT PK_BOOK_AUTHORS PRIMARY KEY (Book_id, Author_name)
);

CREATE TABLE BOOK_COPIES (
  Book_id INTEGER REFERENCES BOOK(Book_id) NOT NULL,
  Branch_id INTEGER REFERENCES LIBRARY_BRANCH(Branch_id) NOT NULL,
  No_of_copies INTEGER,
  CONSTRAINT PK_BOOK_COPIES PRIMARY KEY (Book_id, Branch_id)
);

CREATE TABLE BOOK_LOANS (
  Book_id INTEGER REFERENCES BOOK(Book_id) NOT NULL,
  Branch_id INTEGER REFERENCES LIBRARY_BRANCH(Branch_id) NOT NULL,
  Card_no INTEGER REFERENCES BORROWER(Card_no) NOT NULL,
  Date_out DATE,
  Due_date DATE,
  CONSTRAINT PK_BOOK_LOANS PRIMARY KEY (Book_id, Branch_id, Card_no)
);

-- END OF Library DDL
